### ISSUE TITLE
Review of "Block__Element--Magic: CSS Modularity for the Enterprise."

### ISSUE THREAD

**Issue by jewlofthelotus** [chrisdemars/conference-proposals#1]
> Have you ever been faced with a code base that has been touched by a dozen or more developers all writing code, and as much as you want it to be modular it just isn't? 

I think this would be stronger in the form of a statement - at this point, your target audience probably doesn't even know what modular CSS is. They're probably not thinking "I wish this was modular" they're probably thinking "this code is a hot freaking mess". 

Not saying you have to go this way, but I would experiment with the approach of 1) directly explain the problem and _briefly_ why it happens, 2) offer BEM as the solution and _briefly_ explain why. 

I stressed _briefly_ because you don't want to give it all away in the abstract. The goal is to connect with the reader through relatability, they should be thinking along - "oh yeah, we do have those problems, it's a nightmare.. BEM? hmm this sounds interesting"

> How about when you are tasked with creating different components that make up the different pages, and they all follow the same pattern so ease of code reuse should be straightforward? 

I think my same comments apply for this one. Try as a statement conveying a problem that your audience can nod their heads to. That's the hook. BEM is the line... and sinker? I don't fish... 

If you do go with the statement approach - I'd put both forward first, before offering BEM as the solution.

> BEM is a CSS architecture, methodology, naming convention, whatever the kids are calling it, based off of Object Oriented CSS 

I'd probably remove "whatever the kids are calling it" just because I'd anticipate the audience to be so unfamiliar that a statement like that might just add confusion.

> that makes writing classes more modular and communication better in relationship to the structure and skin of the Web page.

This was a little tricky to grasp as a whole - a more bulleted approach might make the benefits feel stronger: "that makes writing styles x, improves communication by y, and z"

> This talk will focus on basic BEM CSS architecture and how it can be the solution towards modularity within an enterprise environment.

It seems like the enterprise piece of this talk might be somewhat of an afterthought.  I think if you want to role with it, the challenges of an enterprise environment need to be framed as part of the reason we're writing bad CSS, and then the "why is BEM the solution" part should include why it will help deal with challenges of an enterprise environment.  

---

Great first go at an abstract! I get what you're going for and I think with a few structural changes and clarified wording you'll have a strong proposal.

The only other thing I can think to mention is that you might want to include the full words "Block Element Modifier" somewhere.

**Comment by chrisdemars** [comment]
Changed my wording and added things.
