### ISSUE TITLE
grammar / wording edits for "Block, element--magic"

### ISSUE THREAD

**Issue by kroysemaj** [chrisdemars/conference-proposals#2]
Most of my feedback is wording / grammar. I think the basic pitch is good.

> Have you ever been faced with a code base that has been touched by a dozen or more developers all writing code, and as much as you want it to be able to flexible it just isn't? 

This wording seems a little clunky to me. Here's my pass on this particular sentence. 

> Have you ever faced a code base worked on by a more than a dozen developers that is striving for flexibility but never quite gets there? 

These can all be separate sentences.

> B.E.M. is a CSS architecture. It's a methodology. It's a naming convention, and it is based off of Object Oriented CSS. OOCSS makes writing classes more flexible, and modular.

**Comment by chrisdemars** [comment]
I will work on these changes. Thanks!
